//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compiler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compiler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;FUNCTION;
        ///factorial:
        ///; calculates factorial of an input, eax -&gt; eax
        ///	cmp eax, 2
        ///	jge calculate_factorial
        ///	; default return 1
        ///	mov eax, 1
        ///	ret
        ///
        ///calculate_factorial:
        ///	mov ecx, eax
        ///	dec ecx
        ///	; for(ecx = n; ecx &gt; 0; ecx--)
        ///factorial_loop:
        ///	mul ecx
        ///	loop factorial_loop
        ///
        ///	ret
        ///	
        ///;FUNCTION;
        ///print_int:
        ///; prints integer from eax
        ///	push eax
        ///	push format
        ///	call _printf
        ///	add esp, 8
        ///	ret
        ///	
        ///;FUNCTION;
        ///print_float:
        ///; prints float from eax
        ///	mov [__temp], eax
        ///	fld dword [__temp]
        ///	sub esp, 8
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %macro float_comparison 1
        ///; compares two floats from the top of the fpu stack
        ///; input: the status Word Register bits to look at
        ///; important bits: 8-CF, 14-ZF
        ///	xor eax, eax
        ///	; set status register at ax
        ///	fcom   st0, st1
        ///    fstsw  ax	; store status register
        ///	
        ///	; check bits
        ///	and ax, %1
        ///	sete al	; res result
        ///	mov ah, 0
        ///%endmacro.
        /// </summary>
        internal static string Macros {
            get {
                return ResourceManager.GetString("Macros", resourceCulture);
            }
        }
    }
}
